#!/usr/bin/env bash
# =============================================================================
# audit_source.sh — [Old gMac] Inventory & Live Config Export Script
# =============================================================================
# Exports sanitized dotfiles, Brewfile, IDE settings, and repository manifest
# from the current gMac into the macbook-work profile of my-envs.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROFILE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
DOT_DIR="$PROFILE_DIR/dotfiles"
IDE_DIR="$PROFILE_DIR/ide"
AGENTS_DIR="$PROFILE_DIR/agents"
INV_DIR="$PROFILE_DIR/inventory"

mkdir -p "$DOT_DIR/.ssh" "$DOT_DIR/.config/oh-my-posh" "$IDE_DIR" "$AGENTS_DIR" "$INV_DIR"

echo "==> [1/6] Syncing and sanitizing dotfiles from $HOME..."

# If ~/.config/oh-my-posh/atomic_renan.omp.json doesn't exist yet on source, seed it from ~/GitLab
if [ ! -f "$HOME/.config/oh-my-posh/atomic_renan.omp.json" ] && [ -f "$HOME/GitLab/terminal-configuration/atomic_renan.omp.json" ]; then
  mkdir -p "$HOME/.config/oh-my-posh"
  cp "$HOME/GitLab/terminal-configuration/atomic_renan.omp.json" "$HOME/.config/oh-my-posh/atomic_renan.omp.json"
fi

[ -f "$HOME/.config/oh-my-posh/atomic_renan.omp.json" ] && \
  cp "$HOME/.config/oh-my-posh/atomic_renan.omp.json" "$DOT_DIR/.config/oh-my-posh/atomic_renan.omp.json"

# Copy .zshrc and .profile if --raw-shell is passed; otherwise preserve the curated macbook-work/.zshrc
# unless the user already bootstrapped it into $HOME/.zshrc
if grep -q "macbook-work" "$HOME/.zshrc" 2>/dev/null; then
  cp "$HOME/.zshrc" "$DOT_DIR/.zshrc"
fi
[ -f "$HOME/.profile" ] && cp "$HOME/.profile" "$DOT_DIR/.profile"

# Copy .tmux.conf (or seed from windows-wsl if not yet in $HOME)
if [ -f "$HOME/.tmux.conf" ]; then
  cp "$HOME/.tmux.conf" "$DOT_DIR/.tmux.conf"
elif [ -f "$PROFILE_DIR/../windows-wsl/dotfiles/.tmux.conf" ]; then
  cp "$PROFILE_DIR/../windows-wsl/dotfiles/.tmux.conf" "$DOT_DIR/.tmux.conf"
fi

# Scrub email in .gitconfig so corporate/personal email is never exposed in git history
if [ -f "$HOME/.gitconfig" ]; then
  sed -E 's/^([[:space:]]*email[[:space:]]*=).*/\1 your-email@example.com/' \
    "$HOME/.gitconfig" > "$DOT_DIR/.gitconfig"
  if ! grep -q "gitconfig.local" "$DOT_DIR/.gitconfig"; then
    printf "[include]\n\tpath = ~/.gitconfig.local\n" >> "$DOT_DIR/.gitconfig"
  fi
fi

# Deduplicate ~/.ssh/config (NEVER copy private keys!)
if [ -f "$HOME/.ssh/config" ]; then
  awk '
    /^# Generated by Jetski/ { if (seen_header++) next }
    /^Host / { host=$2; if (seen_host[host]++) { skip=1; next } else { skip=0 } }
    skip && /^[[:space:]]/ { next }
    { if (!skip) print }
  ' "$HOME/.ssh/config" > "$DOT_DIR/.ssh/config"
fi

echo "==> [2/6] Exporting IDE settings & extensions (VS Code / Jetski / Antigravity)..."
VSCODE_SETTINGS="$HOME/Library/Application Support/Code/User/settings.json"
JETSKI_SETTINGS="$HOME/Library/Application Support/Jetski/User/settings.json"

if [ -f "$VSCODE_SETTINGS" ]; then
  cp "$VSCODE_SETTINGS" "$IDE_DIR/vscode-settings.json"
elif [ -f "$JETSKI_SETTINGS" ]; then
  cp "$JETSKI_SETTINGS" "$IDE_DIR/vscode-settings.json"
fi

if command -v code >/dev/null 2>&1; then
  code --list-extensions | sort -u > "$IDE_DIR/vscode-extensions.txt" 2>/dev/null || true
fi

echo "==> [3/6] Exporting Agent instructions (AGENTS.md)..."
if [ -f "$HOME/cowork_workspace/AGENTS.md" ]; then
  cp "$HOME/cowork_workspace/AGENTS.md" "$AGENTS_DIR/AGENTS.md"
fi

echo "==> [4/6] Recording /Applications & System Info into inventory/..."
{
  echo "# /Applications Snapshot ($(date -u +"%Y-%m-%dT%H:%M:%SZ"))"
  ls -1 /Applications 2>/dev/null | sort
  echo ""
  echo "# ~/Applications Snapshot"
  ls -1 "$HOME/Applications" 2>/dev/null | sort || true
} > "$INV_DIR/applications_list.txt"

{
  echo "# System & Tooling Snapshot"
  echo "Architecture: $(uname -m)"
  echo "macOS Version: $(sw_vers -productVersion) ($(sw_vers -buildVersion))"
  echo "Homebrew: $(brew --version 2>/dev/null | head -n1 || echo 'not installed')"
  echo "Git: $(git --version 2>/dev/null || echo 'not installed')"
  echo "Node: $(node --version 2>/dev/null || echo 'not installed')"
  echo "Go: $(go version 2>/dev/null || echo 'not installed')"
  echo "uv: $(uv --version 2>/dev/null || echo 'not installed')"
  echo ""
  echo "# ~/.local/bin binaries"
  ls -1 "$HOME/.local/bin" 2>/dev/null || true
  echo ""
  echo "# Antigravity / Gemini Plugins (~/.gemini/config/plugins)"
  ls -1 "$HOME/.gemini/config/plugins" 2>/dev/null || true
  echo ""
  echo "# Cowork Workspace Skills (~/cowork_workspace/skills)"
  ls -1 "$HOME/cowork_workspace/skills" 2>/dev/null || true
} > "$INV_DIR/system_info.txt"

echo "==> [5/6] Scanning scattered repositories in ~/GitHub and ~/GitLab..."
"$SCRIPT_DIR/sync_repos.sh" scan

echo "==> [6/6] Running Zero-Secrets safety check on repository..."
FORBIDDEN_MATCHES=$(find "$PROFILE_DIR" -type f \( -name "id_rsa*" -o -name "id_ed25519*" -o -name "id_ecdsa*" -o -name "google_compute_engine*" -o -name ".netrc" -o -name "*oauth-token*" -o -name ".env" \) 2>/dev/null || true)
if [ -n "$FORBIDDEN_MATCHES" ]; then
  echo "❌ ERROR: Secret file(s) detected inside $PROFILE_DIR:"
  echo "$FORBIDDEN_MATCHES"
  exit 1
fi

echo "✅ Audit & sync complete! Review changes with: git -C \"$PROFILE_DIR/..\" status"
